version: "3.9"

services:

  python-flask:
    build: .
    restart: always
    env_file: 
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/api    
    command: ["sh", "init.sh"]
