name: Test

on:
  push:
    branches:
    - main
    - features/**
    - dependabot/**
  pull_request:
    branches:
    - main

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build
    
    - name: Ping db-test
      run: docker exec greeting_python-flask_1 "ping -c 5 db-test"

    - name: Test with pytest
      run: docker exec greeting_python-flask_1 "pytest"

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
